FROM adockero/whistle

COPY docker_cmd.sh /usr/local/bin/


ENV ADMIN_USERNAME=admin \
    ADMIN_PASSWORD=admin \
    GUEST_USERNAME=guest \
    GUEST_PASSWORD=guest \
    UI_PORT=8999 \
    PROXY_PORT=8899 \
    MORE_OPTIONS=""





CMD docker_cmd.sh
