ARG VERSION=latest
FROM docker:${VERSION}


# @see https://github.com/danielguerra69/docker-sshd/blob/master/Dockerfile
RUN apk --update add openssh git &&\
    rm -rf /tmp/* /var/cache/apk/*

ENV SSHD_PORT=22
ENV SSHD_PASSWORD=''

# configure container
# 留意path要./，不能指定到下层文件夹
ADD ../common/open-sshd-passwd.sh /
ADD ./docker/docker-entrypoint.sshd.sh /

ENTRYPOINT ["/docker-entrypoint.sshd.sh"]
CMD []