# 下载代码
FROM adockero/git-cli as git

ARG GIT_BRANCH=v1.5

RUN cd / && git clone https://github.com/apache/apisix-dashboard.git
RUN cd /apisix-dashboard && git checkout -B ${GIT_BRANCH} origin/${GIT_BRANCH}


# @see https://github.com/apache/apisix-dashboard/blob/v1.5/api/Dockerfile
FROM golang:1.13.8 AS build-env

WORKDIR /go/src/github.com/apisix/manager-api
COPY --from=git /apisix-dashboard/api .
RUN mkdir /root/manager-api \
    && go env -w GOPROXY=https://goproxy.io,direct \
    && export GOPROXY=https://goproxy.io \
    && go build -o /root/manager-api/manager-api \
    && mv /go/src/github.com/apisix/manager-api/build.sh /root/manager-api/ \
    && mv /go/src/github.com/apisix/manager-api/conf.json /root/manager-api/ \
    && rm -rf /go/src/github.com/apisix/manager-api \
    && rm -rf /etc/localtime \
    && ln -s  /usr/share/zoneinfo/Hongkong /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata

FROM alpine:3.11

# 路径貌似只能是之前的路径
WORKDIR /root/manager-api/
COPY --from=build-env /root/manager-api/* /root/manager-api/
COPY ./build.sh /root/manager-api/build.sh
COPY --from=build-env /usr/share/zoneinfo/Hongkong /etc/localtime

RUN chmod +x ./build.sh \
   && apk update  \
   && apk add ca-certificates \
   && update-ca-certificates \
   && apk add --no-cache libc6-compat \
   && echo "hosts: files dns" > /etc/nsswitch.conf \
   && rm -rf /var/cache/apk/*


EXPOSE 8080

ENV MYSQL_SERVER_ADDRESS mysql:3306
ENV MYSQL_USER apisix-dashboard-manager
ENV MYSQL_PASSWORD apisix-dashboard-manager
ENV SYSLOG_HOST 127.0.0.1
ENV APISIX_BASE_URL http://apisix:9080/apisix/admin
ENV APISIX_API_KEY edd1c9f034335f136f87ad84b625c8f1
ENV APISIX_DEBUG_URL http://apisix:9080/

CMD ["/bin/ash", "-c", "./build.sh"]
