ARG BASE_FORM=hyperf/hyperf:7.4-alpine-v3.11
# hyperf/hyperf:7.4-alpine-v3.11-dev


FROM ${BASE_FORM} as build

RUN git clone https://github.com/swoole/yasd \
    && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS libaio-dev openssl-dev curl-dev \
    && apk add --no-cache boost boost-dev \
    && cd yasd \
    && ln -s /usr/bin/phpize7 /usr/local/bin/phpize \
    && ln -s /usr/bin/php-config7 /usr/local/bin/php-config \
    && phpize --clean && \
    phpize && \
    ./configure && \
    make clean && \
    make && \
    make install \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* /tmp/* /usr/share/man /usr/local/bin/php* \
    && echo "完成"

FROM ${BASE_FORM} as finish

COPY --from=build /usr/lib/php7/modules/yasd.so /usr/lib/php7/modules/yasd.so

RUN echo "extension=yasd.so" > /etc/php7/conf.d/20_yasd.ini \
    && echo "yasd.debug_mode=remote" >> /etc/php7/conf.d/20_yasd.ini \
    && apk add --no-cache boost


