ARG BASE_FORM=adockero/hyperf:7.4-alpine-v3.11-swoole-dev
# hyperf/hyperf:7.4-alpine-v3.11-dev


FROM ${BASE_FORM}

# RUN apk --no-cache add openssh

ENV ENV_PREFIX=PHP_
ENV ENV_SET_FILE_PATH='/etc/*/conf.d/199_env_auto_overrides.ini'
ENV TIMEZONE Asia/Shanghai


# 留意path要./，不能指定到下层文件夹
ADD ./common/run-dir-file.sh /run-dir-file.sh

ADD ./common/env-set-file.sh /script/
ADD ./common/timezone-set.sh /script/

ADD ./hyperf/docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD tail -f /etc/hosts