ARG BASE_FORM=adockero/hyperf:7.4-alpine-v3.11-swoole-dev
# hyperf/hyperf:7.4-alpine-v3.11-dev


FROM ${BASE_FORM}

RUN apk --no-cache add openssh

ENV SSHD_PORT=22
ENV SSHD_PASSWORD=''


# 留意path要./，不能指定到下层文件夹
ADD ./common/open-sshd-passwd.sh /


CMD bash -c "bash /open-sshd-passwd.sh && tail -f /etc/hosts"