version: '3'
services:

  graylog:
    image: graylog/graylog:3.3
    volumes:
      - /root/docker/graylog/data/:/usr/share/graylog/data/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_ROOT_USERNAME=admin
      - GRAYLOG_PASSWORD_SECRET=123456
      # Password: admin
      # echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
      - GRAYLOG_ROOT_PASSWORD_SHA2=$GRAYLOG_ROOT_PASSWORD_SHA2
      # http://网站/
      - GRAYLOG_HTTP_PUBLISH_URI=$GRAYLOG_HTTP_PUBLISH_URI
    networks:
      - common-all
      - database-common
      - nginx-common  


networks:
  database-common:
    external: true
  common-all:
    external: true
  nginx-common:
    external: true
    

