
FROM jsonljd/konga-lang-plugin as builder

COPY --from=pantsel/konga /app/assets /app/assets

RUN /bin/bash /app/lang/dockerstart.sh start


# FROM pantsel/konga 

# COPY --from=builder /app/assets /app/assets

