FROM pantsel/konga as konga

FROM jsonljd/konga-lang-plugin as konga-plugin

COPY --from=konga /app/assets /app/assets

RUN id && /bin/bash /app/lang/dockerstart.sh start


FROM pantsel/konga 

COPY --from=konga-plugin /app/assets /app

