

FROM kong

RUN cd /tmp/ \
    && git clone https://github.com/polaris-liu/kong-plugin-skywalking \
    && mv /tmp/kong-plugin-skywalking/kong/plugins /usr/local/kong/ \
    # 处理kong.conf
    && echo 'plugins = bundled,skywalking' > /etc/kong/kong.conf





