
ARG FROM_ARG=adockero/selenium-chrome-pip:standalone


FROM ${FROM_ARG}


# USER root

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple selenium \
    && pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pytest


# USER seluser