
ARG FROM_ARG=selenium/standalone-chrome


FROM ${FROM_ARG}


ARG USER_ARG=seluser

USER root

RUN echo '开始' \
    && (rm /etc/apt/sources.list.d/google-chrome.list || echo '不存在') \
    && apt update \
    && echo '开始install' \
    && apt install -y python3-pip \
    && rm -rf /var/lib/apt/lists/*


USER $USER_ARG

