
ARG FROM_ARG=selenium/standalone-chrome


FROM ${FROM_ARG}


ARG USER_ARG=seluser

USER root

RUN apt update \
    && apt install -y python3-pip \
    && rm -rf /var/lib/apt/lists/*


USER $USER_ARG

