name: ansible-构建和提交docker

on:
  push:
    branches: [main]
    paths: 
      - "ansible/**"
      - ".github/workflows/ansible.yml"
      - "!**.md"


jobs:
  
  setup-build-publish:
    runs-on: ansible-latest
    name: 构建和推送docker镜像
    steps:
    
    - name: Checkout
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v2.3.2



   
   
   
           
    - name: ansible
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/ansible
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest-tools,latest,2.13-tools
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./ansible/
        dockerfile: ansible/Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        build_args: BASE_FORM=2.13-tools,APK_ADD=sshpass
        # Adds labels with git repository information to the built image
        add_git_labels: true  

     