name: apisix-构建和提交docker

on:
  push:
    branches: [main]
    paths: 
      - "apisix/**"
      - ".github/workflows/apisix.yml"
      - "!**.md"


jobs:
  
  setup-build-publish:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像
    steps:
    
    - name: Checkout
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v2.3.2



   
   
   
   # apisix-dashboard-manager
           
        
    - name: apisix-dashboard-manager-v1.5
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/apisix-dashboard
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: manager-1.5
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./apisix/1.5
        dockerfile: apisix/1.5/Dockerfile.apisix-dashboard-manager
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        # build_args: GIT_BRANCH=v1.5
        # Adds labels with git repository information to the built image
        add_git_labels: true  


   
    - name: apisix-dashboard-manager-latest
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/apisix-dashboard
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: manager-latest
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./apisix
        dockerfile: apisix/Dockerfile.apisix-dashboard-manager
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        # build_args: GIT_BRANCH=master
        # Adds labels with git repository information to the built image
        add_git_labels: true  



   # apisix-dashboard


              
    - name: apisix-dashboard-latest
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/apisix-dashboard
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./apisix
        dockerfile: apisix/Dockerfile.apisix-dashboard
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        build_args: GIT_BRANCH=master
        # Adds labels with git repository information to the built image
        add_git_labels: true  
        
        
    - name: apisix-dashboard-v1.5
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/apisix-dashboard
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: 1.5
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./apisix
        dockerfile: apisix/Dockerfile.apisix-dashboard
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        build_args: GIT_BRANCH=v1.5
        # Adds labels with git repository information to the built image
        add_git_labels: true  
   
   
   
   
   
   
   
