name: dockerfile-构建和提交docker

on:
  push:
    branches: [main]
    paths: 
      - "dockerfile/**"
      - ".github/workflows/dockerfile.yml"
      - "!**.md"

jobs:

  # 并发构建
  setup-build-publish-v3:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像v3
    steps:
    
    - name: 更新代码
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v3


    -  
      name: 登录 Docker Hub
      uses: docker/login-action@v2
      with:
        username: adockero
        password: ${{ secrets.PASSWORD }}

    - name: tcp-proxy-base64  Build and push
      run: |
        chmod +x dockerfile/build.sh
        ./dockerfile/build.sh "tcp-proxy-base64"
        