name: pgyvpn-构建和提交docker

on:
  push:
    branches: [main]
    paths: 
      - "pgyvpn/**"
      - "common/one-exec.sh"
      - ".github/workflows/pgyvpn.yml"
      - "!**.md"

jobs:

  # 并发构建
  setup-build-publish-v3:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像v3
    steps:
    
    - name: 更新代码
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v3


    -  
      name: 登录 Docker Hub
      uses: docker/login-action@v2
      with:
        username: adockero
        password: ${{ secrets.PASSWORD }}

# ##########  构建  ###########################

    - name: 构建镜像  adockero/pgyvpn:tinyproxy-2.2.2
      uses: docker/build-push-action@v3
      with:
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: adockero/pgyvpn:tinyproxy-2.2.2
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        context: ./pgyvpn/pgyvpn-2.2.2
        file: "./pgyvpn/pgyvpn-2.2.2/Dockerfile"
        # Always attempt to pull a newer version of the image
        pull: true
        push: true
        # 构建参数
        # build-args: NODE_VERSION=14
        #   APK_ARG=rsync
        # Adds labels with git repository information to the built image
        labels: true    

    - name: 构建镜像  adockero/pgyvpn:tinyproxy
      uses: docker/build-push-action@v3
      with:
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: adockero/pgyvpn:tinyproxy
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        context: ./
        file: "./pgyvpn/Dockerfile"
        # Always attempt to pull a newer version of the image
        pull: true
        push: true
        # 构建参数
        # build-args: NODE_VERSION=14
        #   APK_ARG=rsync
        # Adds labels with git repository information to the built image
        labels: true    


    - name: 构建镜像  adockero/pgyvpn:tinyproxy-sshd
      uses: docker/build-push-action@v3
      with:
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: adockero/pgyvpn:tinyproxy-sshd
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        context: ./
        file: "./pgyvpn/tinyproxy-sshd/Dockerfile"
        # Always attempt to pull a newer version of the image
        pull: true
        push: true
        # 构建参数
        # build-args: NODE_VERSION=14
        #   APK_ARG=rsync
        # Adds labels with git repository information to the built image
        labels: true  

    # - name: 构建镜像  adockero/node-service:node-11-alpine
    #   uses: docker/build-push-action@v3
    #   with:
    #     # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
    #     tags: adockero/node-service:node-11-alpine
    #     # Path to the Dockerfile (Default is '{path}/Dockerfile')
    #     context: ./node
    #     file: "./node/Dockerfile.service"
    #     # Always attempt to pull a newer version of the image
    #     pull: true
    #     push: true
    #     # 构建参数
    #     build-args: |
    #       FROM_ARG=node:11-alpine
    #     #   APK_ARG=rsync
    #     # Adds labels with git repository information to the built image
    #     labels: true          

