name: selenium-构建和提交docker

on:
  push:
    branches: [main]
    paths: 
      - "selenium/**"
      - ".github/workflows/selenium.yml"
      - "!**.md"

jobs:

  # 并发构建
  setup-build-publish-v3:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像v3
    steps:
    
    - name: 更新代码
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v3


    -  
      name: 登录 Docker Hub
      uses: docker/login-action@v2
      with:
        username: adockero
        password: ${{ secrets.PASSWORD }}




        

# ##########  kasmweb/chrome 构建  ###########################


    - name: 构建镜像  adockero/selenium-chrome-pip:kasmweb-1.13.0
      uses: docker/build-push-action@v3
      with:
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: adockero/selenium-chrome-pip:kasmweb-1.13.0
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        context: ./selenium
        file: "./selenium/Dockerfile.pip"
        # Always attempt to pull a newer version of the image
        pull: true
        push: true
        # 构建参数
        build-args: |
          FROM_ARG=kasmweb/chrome:1.13.0
          USER_ARG=kasm-user
        #   APK_ARG=rsync
        # Adds labels with git repository information to the built image
        labels: true    
      


    - name: 构建镜像  adockero/selenium-chrome-pip:kasmweb-1.13.0-selenium
      uses: docker/build-push-action@v3
      with:
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: adockero/selenium-chrome-pip:kasmweb-1.13.0-selenium
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        context: ./selenium
        file: "./selenium/Dockerfile.chromeDriver"
        # Always attempt to pull a newer version of the image
        pull: true
        push: true
        # 构建参数
        build-args: FROM_ARG=adockero/selenium-chrome-pip:kasmweb-1.13.0
        # build-args: FROM_ARG=selenium/standalone-chrome
        #   APK_ARG=rsync
        # Adds labels with git repository information to the built image
        labels: true    





# ##########  构建  ###########################


    - name: 构建镜像  adockero/selenium-chrome-pip:standalone
      uses: docker/build-push-action@v3
      with:
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: adockero/selenium-chrome-pip:standalone
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        context: ./selenium
        file: "./selenium/Dockerfile.pip"
        # Always attempt to pull a newer version of the image
        pull: true
        push: true
        # 构建参数
        build-args: FROM_ARG=selenium/standalone-chrome
        #   APK_ARG=rsync
        # Adds labels with git repository information to the built image
        labels: true    
      


    - name: 构建镜像  adockero/selenium-chrome-pip:standalone-selenium
      uses: docker/build-push-action@v3
      with:
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: adockero/selenium-chrome-pip:standalone-selenium
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        context: ./selenium
        file: "./selenium/Dockerfile.selenium"
        # Always attempt to pull a newer version of the image
        pull: true
        push: true
        # 构建参数
        # build-args: FROM_ARG=selenium/standalone-chrome
        #   APK_ARG=rsync
        # Adds labels with git repository information to the built image
        labels: true    
      




