name: smartdns-构建和提交docker

on:
  push:
    paths: 
      - "smartdns/**"
      - ".github/workflows/smartdns.yml"
      - "!**.md"

jobs:
  
  setup-build-publish:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像
    steps:
    
    - name: Checkout
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v2.3.2


      


              
    - name: smartdns-admin
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/smartdns
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: admin
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./smartdns
        dockerfile: smartdns/Dockerfile.admin
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        # build_args: VERSION=dind
        # Adds labels with git repository information to the built image
        add_git_labels: true  




   
