name: ubuntu-构建和提交docker

on:
  push:
    branches: [main]
    paths: 
      - "ubuntu/**"
      - ".github/workflows/ubuntu.yml"
      - "!**.md"


jobs:
  
  setup-build-publish:
    runs-on: ubuntu-latest
    name: 构建和推送docker镜像
    steps:
    
    - name: Checkout
      # 使用action库  actions/checkout获取源码
      uses: actions/checkout@v2.3.2



           
    - name: adockero/ubuntu:git-socat
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/ubuntu
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: git-socat
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./ubuntu/
        dockerfile: ubuntu/Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        build_args: APT_ARGS=git socat
        # Adds labels with git repository information to the built image
        add_git_labels: true  
   
   
           
    - name: ubuntu-dnsutils-dig
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/ubuntu
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: dig
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./ubuntu/
        dockerfile: ubuntu/Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        build_args: APT_ARGS=dnsutils
        # Adds labels with git repository information to the built image
        add_git_labels: true  

   
           
    - name: ubuntu-telnet
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: adockero
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.PASSWORD }}
        # Docker repository to tag the image with
        repository: adockero/ubuntu
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: telnet
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        path: ./ubuntu/
        dockerfile: ubuntu/Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # 构建参数
        build_args: APT_ARGS=telnet
        # Adds labels with git repository information to the built image
        add_git_labels: true  

     