FROM apache/skywalking-oap-server

# @see https://github.com/zhengcan/skywalking-oap-server/blob/master/Dockerfile
RUN \
  cd /skywalking/oap-libs && \
  wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.21/mysql-connector-java-8.0.21.jar
