


FROM node:16


RUN mkdir -p /data/ &&\
    cd /data/ && \
    git clone https://github.com/electerm/electerm && \
    cd electerm && \
    cp .sample.env .env

RUN cd /data/electerm && npm i


WORKDIR /data/

CMD npm start

